### PR TITLE
Fix menu typo

### PR DESCRIPTION
**Pull request by tjrana**
Fix small typo in menu from `Checking for update...` to `Checking for updates...`.

### CODE REVIEW

**Comment by tjrana** [comment]
Oh, then it could have been written as "Checking for an update..."
I see a lot of other software use "Check for Updates..." as a menu option.

**Comment by mobitar** [comment]
Possibly. I'd have to think about this one.

**Comment by tjrana** [comment]
Additionally, the menu title is originally "Updates", so it would make sense to keep it plural.

**Comment by tjrana** [comment]
@mobitar Please let me know if you'd like me to close this pull request.

**Comment by mobitar** [comment]
Yes, feel free to close. We'll probably come back to this in the future. Appreciate your attention to detail!

**Pull request closed without merging**
