### PR TITLE
standardnotes/desktop is now available in the AUR!

### PR DESCRIPTION
**Pull request by JoshuaRLi**
Hey Mo!

Starting from 2.0.42 I'll be maintaining an AUR package for the AppImage. I've added a link in the README and also cleaned it up a bit.

### CODE REVIEW

**Comment by mobitar** [comment]
Hey, sweet! Can you tell me a little more about AUR packages? I'm not too familiar with them..

**Comment by JoshuaRLi** [comment]
Arch Linux has a main binary repository, and a much larger Arch User Repository (AUR) which does not contain neither source code nor binaries, but `PKGBUILD`s. A `PKGBUILD` is a shell script that defines build information for `makepkg`, the utility which builds packages installable by Arch's package manager, `pacman`. More info [here](https://wiki.archlinux.org/index.php/PKGBUILD).

So I created a `PKGBUILD` [here](https://aur.archlinux.org/packages/sn-bin/) that basically downloads the latest release binary from the Releases page and installs it to `/usr/bin/`.

Downloading the `PKGBUILD`, using `makepkg` and `pacman` is a manual workflow, and people use "AUR helpers" like `pacaur` to download AUR packages (now you can `pacaur -S sn-bin` to install Standard Notes). The AUR is not officially supported by core Arch Linux and so `pacman` cannot install directly from the AUR.

**Comment by mobitar** [comment]
Ok cool, well, I like most of the changes in the PR but I think I'd like to keep the actual command instead of "and give it executable permission" since not everyone will know what that means or what the command for that is.

Also, I'd like to see how well-maintained we can keep this before advertising it in any official capacity. Because once people depend on something, it's hard to take it away. So my goal is to form as few dependencies as possible. Is there a better way people typically find out about AUR packages?

**Comment by JoshuaRLi** [comment]
What do you mean by "form as few dependencies as possible"? The `PKGBUILD` is not downloading source and building, it basically downloads the AppImage and installs it.

No, not really. The only ways I know of to discover AUR packages are:
* There is an Arch Wiki page on the software and it includes a link to the AUR
* A link to the AUR is included in the project `README`

**Comment by mobitar** [comment]
What I meant by dependencies was more metaphorical, meaning, I don't want users to depend on having this AUR package available, then, one day, because you no longer have time to keep it up to date, these users are now left hanging. Whereas by never introducing that "dependency" in the first place, this problem would have never occurred.

But, a small link in a readme is reasonable enough. Can you just mention that the repo is maintained by a third party? Something like "as a third-party maintained package on AUR...".

**Comment by JoshuaRLi** [comment]
I see, valid point. I've updated the `README` in accordance.

**Comment by mobitar** [comment]
How about, since I believe there are a few other packages (like brew, etc), we make a standardized section for it. Something like:

## Other ways to download
- AUR package (maintained independently by @JoshuaRLi)
- future package here (maintained independently by ...)

**Comment by JoshuaRLi** [comment]
Sure thing, I'll use the section title "Alternative Downloads" though.

**Comment by mobitar** [comment]
👌

**Pull request merged**
