### PR TITLE
[shortcuts] Map web shortcut to common shortcut for native

### PR DESCRIPTION
**Pull request by nil1511**
Map desktop native shortcut to Web `keyboardManager` shortcuts

- New note `CmdOrCtrl+N`
- Focus Search `CmdOrCtrl+F`

### CODE REVIEW

**Comment by mobitar** [comment]
Hey @nil1511, thanks for the PR. I'm not understanding its motivation however. The web project does support keyboard shortcuts in their basic form, however, some of these shortcuts don't work on Windows properly currently (the keyboard shortcuts feature was released quietly as a way to gather feedback). But, the solution to this wouldn't be to handle this on the Electron level, but to instead fix these shortcuts on the [web side](https://github.com/standardnotes/web/blob/master/app/assets/javascripts/app/controllers/notes.js#L620) of things.

**Comment by nil1511** [comment]
I wasn't aware of the windows issue. In the mac native app, I could not find basic shortcuts. They were not available in the menu then looking in the source code, I found about `keyboardManager` and mapped them to edit menu with the intutive shortcut. Still missing a few shortcuts like lock, archive selected note.

**Comment by mobitar** [comment]
Right, the keyboardManager is a new feature with only a few key shortcuts. We'll be expanding this in the near future once we solidify how we want it to behave. But offering menu items like you have in this PR is an interesting idea. Hadn't considered that before. Will keep this in mind as we look to improve this area.

**Comment by mogwai** [comment]
I'm using the native linux app and would love to see keybindings added. Perhaps following a vscode format for keybinds in that you can customise them easily?

**Comment by baptiste-grob** [comment]
Key bindings are on our roadmap, but we're still in the planning stages with our designer @zsoltszilvai. Tagging him so he can see this thread and take notes!

**Pull request closed without merging**
