### PR TITLE
Auto hide the menu bar

### LINKED ISSUE #96: [Feature Request] Option to hide the menu bar
Could you please consider adding an option to hide the menu bar within the view settings? It could be displayed again by pressing the Alt key. This is standard behavior across many apps (Firefox and Atom to name a few), offering a less cluttered experience and a little extra vertical space.

### PR DESCRIPTION
**Pull request by aden-young**
Resolves #96, menu bar is auto hidden when the app is started, can be shown using the alt key, and can be toggled to show at all times via the view menu.

### CODE REVIEW

**Comment by mobitar** [comment]
Thanks @aden-young. This won't have any effect on Mac though, so we'll need to only display this option only for non-Mac OSes. Which platforms have you tested this on? Do you have a screengrab of how it functions?

**Comment by aden-young** [comment]
No problems @mobitar, I've added a condition so this doesn't appear on Mac OS, and I've tested this on Ubuntu 17.10 and Mac OS Sierra. You can see a video of how this functions here: [https://www.dropbox.com/s/o566jsxta32ayqz/standardnotes_menubar.webm?dl=0](url)

**Comment by aden-young** [comment]
Thanks! To answer your questions:

I do believe the Alt key is a well known shortcut for accessing an app menu, it's the default behaviour of a large number of apps including Firefox, Slack, Atom, and it's even the default behaviour of the '[autoHideMenuBar](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions)' function built into electron.

With that said, when the menu bar is hidden by default there's no clear indicator that there is a menu, or how to access it, to work around this I've changed the behaviour to show the menu bar by default, and I've renamed the menu item to say "Hide Menu Bar" with the subtext "Show again with Alt key" (as this menu item will not be displayed on Mac systems, I haven't made this platform specific).

You can see a video of this in action here:
[standardnotes_menubar_option.webm](https://www.dropbox.com/s/0k4l0edpfy0m04r/standardnotes_menubar_option.webm?dl=0)

Let me know what you think of this implementation, there's probably a few different ways to achieve this depending on how you'd like the defaults to be set, but the above should be the most straightforward for the moment.

**Comment by mobitar** [comment]
Hmm..the subtitle in the menu item doesn't feel very idiomatic. Were you not able to put a shortcut icon on the right side of the cell?

**Comment by aden-young** [comment]
Unfortunately not, that shortcut icon on the right hand of the menu item is only shown when there is an actual keyboard shortcut set using an "accelerator", and the Alt key on it's own is unable to be set as an accelerator, as it needs to be paired with another key.

As a result, I've set up 'Alt + m' as a keyboard shortcut to show/hide the menubar manually, instead of toggling the "autoHideMenuBar" function in electron, you can see this in action here:
[standardnotes_menubar_altm.webm](https://www.dropbox.com/s/845rcp4wnzatnt5/standardnotes_menubar_altm.webm?dl=0)

This will make for a more consistent keyboard shortcut, rather than the Alt key doing nothing while the menu is visible, and then showing/hiding when the "autohide" functionality if in effect.

Let me know what your thoughts are.

**Comment by mobitar** [comment]
Just tested on Windows and Linux, works great! Nice work.

**Pull request merged**
